name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"
